### ISSUE TITLE
Uncaught TypeError: view.makeDismissable is not a function

### ISSUE THREAD

**Issue by akapa100** [UziTech/notifications#2]
[Enter steps to reproduce:]

1. ...Check Notifications Log
2. ...Click anywhere in the Log

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [notifications-plus](https://github.com/UziTech/notifications) package 0.69.4

### Stack Trace

Uncaught TypeError: view.makeDismissable is not a function

```
At C:\Users\Pedro\.atom\packages\notifications-plus\lib\main.coffee:117

TypeError: view.makeDismissable is not a function
    at /packages/notifications-plus/lib/main.coffee:117:12
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/notifications-plus/lib/notifications-log.coffee:94:33
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/notifications-plus/lib/notifications-log-item.coffee:31:18)
```

### Commands

```
  9x -3:28.3.0 core:backspace (input.hidden-input)
     -3:24.3.0 autocomplete-plus:confirm (input.hidden-input)
     -3:24.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:23.6.0 intentions:highlight (input.hidden-input)
  2x -3:23.5.0 core:undo (input.hidden-input)
     -3:09.6.0 intentions:highlight (input.hidden-input)
     -3:09.1.0 settings-view:open (input.hidden-input)
     -3:06.3.0 core:paste (input.hidden-input)
     -2:13.2.0 atom-ternjs:openConfig (div.package-detail.panels-item)
     -2:01.2.0 atom-ternjs:restart (div.package-detail.panels-item)
  2x -1:57.9.0 atom-ternjs:openConfig (div.package-detail.panels-item)
     -1:02.5.0 intentions:highlight (input.hidden-input)
     -1:02.3.0 settings-view:open (input.hidden-input)
     -0:53.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:49.3.0 sync-settings:backup (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:41.4.0 notifications-plus:toggle-log (a.notifications-count.inline-block)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
autoclose-html 0.23.0 
autocomplete-modules 1.7.0 
autocomplete-paths 2.11.0 
blade-snippets 0.2.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.11 
git-blame 1.2.2 
git-plus 7.9.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
hyperclick 0.1.5 
increment-selection 0.3.0 
intentions 1.1.5 
language-blade 0.34.0 
language-vue 0.23.1 
laravel 0.7.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jshint 3.1.5 
linter-markdown 5.2.0 
linter-php 1.4.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
notifications-plus 0.69.4 
php-getters-setters 0.5.5 
pigments 0.40.2 
project-manager 3.3.5 
quick-highlight 0.10.0 
Remote-FTP 1.1.3 
simple-drag-drop-text 0.3.4 
sort-lines 0.15.0 
sync-settings 0.8.3 
tasks 2.6.7 
todo-show 2.0.0 
toggle-quotes 1.0.1 
toggler 0.3.0 
wordcount 2.10.4 
```

**Comment by UziTech** [comment]
this seems to be an issue with notifications being enabled when atom starts. Try v0.69.5 and see if that fixes the issue

**Comment by akapa100** [comment]
Thanks Issue Solved
